"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'ml' | 'mr' | 'bn' | 'gu' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav_home": "Home",
    "nav_trip_planner": "AI Trip Planner",
    "nav_map_search": "Map Search",
    "nav_about": "About",
    "nav_profile": "Profile",
    "profile_title": "My Profile",
    "profile_trips": "My Trip History",
    "profile_trips_desc": "View your recent AI-planned journeys.",
    "profile_no_trips": "No trips found",
    "profile_no_trips_desc": "You haven't planned any trips yet.",
    "profile_plan_trip": "Plan a Trip",
    "profile_sign_out": "Sign Out",
    "profile_account_type": "Account Type",
    "profile_standard_member": "Standard Member",
    "profile_language": "Preferred Language",
    "hero_title": "Navigate With Vibrant Power.",
    "hero_subtitle": "We've brought color and intelligence to urban transit. Track every bus, plan every trip, and enjoy every mile.",
    "hero_cta": "Plan Your Trip",
    "stats_commuters": "Daily Commuters",
    "stats_routes": "Active Routes",
    "stats_buses": "Live Buses",
    "stats_time": "Time Saved",
    "feature_ai_title": "AI Trip Planner",
    "feature_ai_desc": "Our revolutionary AI analyzes traffic and routes to suggest the perfect journey.",
    "feature_map_title": "Global Radar",
    "feature_map_desc": "Discover verified stops and transit hubs directly on our interactive map.",
    "planner_start": "Start Location",
    "planner_dest": "Destination",
    "planner_notes": "Additional Notes",
    "planner_button": "Generate AI Trip Plan",
    "planner_loading": "AI is brainstorming your route...",
    "planner_summary": "Trip Summary",
    "planner_eta": "Estimated Arrival",
    "planner_cost": "Estimated Cost",
    "footer_contact": "Say Hello",
    "hero_badge": "Premium Commuting Experience",
    "hero_title_1": "Navigate With ",
    "hero_title_2": "Vibrant Power.",
    "cta_title_1": "Don't just commute.",
    "cta_title_2": "Dominate",
    "cta_title_3": " the tracks.",
    "cta_subtitle": "Ready to embrace the most colorful and efficient transit experience ever created? Your bus is waiting.",
    "cta_button_primary": "Join Now — It's Free",
    "cta_button_secondary": "Our Vision",
    "feature_map_badge": "Interactive",
    "feature_safe_title": "Safe & Secure",
    "feature_safe_desc": "Advanced safety features and incident response tools to ensure a safe journey.",
    "feature_alarm_title": "Destination Alarm",
    "feature_alarm_desc": "Mark your destination stop and let us wake you up when you arrive.",
    "feature_community_title": "Community Driven",
    "feature_community_desc": "Contribute to the network by reporting conditions and verifying live details.",
    "feature_crowd_title": "Crowd Insights",
    "feature_crowd_desc": "Know how full a bus is before it arrives with real-time occupancy tracking.",
    "feature_alerts_title": "Service Alerts",
    "feature_alerts_desc": "Stay ahead of delays, detours, and weather disruptions on your route.",
    "feature_nearby_title": "Nearby Stands",
    "feature_nearby_desc": "Instantly find every bus stand near you on Google Maps for the most accurate details.",
    "map_initializing": "Initializing Map Service...",
    "map_back_home": "Back Home",
    "map_search_placeholder": "Search destinations, bus stands, cities...",
    "map_directions": "Get Directions",
    "cta_plan_smartly": "Plan Smartly",
    "cta_explore_map": "Explore Map",
    "cta_learn_more": "Learn More",
    "cta_set_alarm": "Set Alarm",
    "cta_join_us": "Join Us",
    "cta_check_occupancy": "Check Occupancy",
    "cta_view_alerts": "View Alerts",
    "cta_show_nearby": "Show Nearby",
    "feature_smart_badge": "Smart",
    "feature_trusted_badge": "Trusted",
    "feature_onboard_badge": "Onboard",
    "feature_social_badge": "Social",
    "feature_critical_badge": "Critical",
    "feature_external_badge": "External",
    "feature_experience_badge": "Our Experience",
    "feature_hero_title_1": "Designed For The",
    "feature_hero_title_2": "Bold",
    "feature_hero_title_3": "Commuter.",
    "feature_hero_desc": "We didn't just build a tracker. We built a vibrant companion that guides you through the urban jungle with style and precision.",
    "cta_rated_badge": "Rated 4.9/5 by Users",
    "cta_city_approved": "City Approved",
    "cta_stat_1": "Transit Efficiency",
    "cta_stat_2": "Network Coverage",
    "cta_stat_3": "Community Growth",
  },
  hi: {
    "nav_home": "होम",
    "nav_trip_planner": "AI ट्रिप प्लानर",
    "nav_map_search": "मैप सर्च",
    "nav_about": "हमारे बारे में",
    "nav_profile": "प्रोफ़ाइल",
    "profile_title": "मेरी प्रोफ़ाइल",
    "profile_trips": "मेरा यात्रा इतिहास",
    "profile_trips_desc": "अपनी हाल की AI-नियोजित यात्राएं देखें।",
    "profile_no_trips": "कोई यात्रा नहीं मिली",
    "profile_no_trips_desc": "आपने अभी तक किसी यात्रा की योजना नहीं बनाई है।",
    "profile_plan_trip": "यात्रा की योजना बनाएं",
    "profile_sign_out": "साइन आउट",
    "profile_account_type": "खाता प्रकार",
    "profile_standard_member": "मानक सदस्य",
    "profile_language": "पसंदीदा भाषा",
    "hero_title": "वाइब्रेंट पावर के साथ नेविगेट करें।",
    "hero_subtitle": "हमने शहरी ट्रांजिट में रंग और बुद्धिमत्ता लाई है। हर बस को ट्रैक करें, हर यात्रा की योजना बनाएं और हर मील का आनंद लें।",
    "hero_cta": "अपनी यात्रा की योजना बनाएं",
    "stats_commuters": "दैनिक यात्री",
    "stats_routes": "सक्रिय मार्ग",
    "stats_buses": "लाइव बसें",
    "stats_time": "समय की बचत",
    "feature_ai_title": "AI ट्रिप प्लानर",
    "feature_ai_desc": "हमारा क्रांतिकारी AI सही यात्रा का सुझाव देने के लिए ट्रैफिक और मार्गों का विश्लेषण करता है।",
    "feature_map_title": "ग्लोबल रडार",
    "feature_map_desc": "सीधे हमारे इंटरैक्टिव मानचित्र पर सत्यापित स्टॉप और ट्रांजिट हब खोजें।",
    "planner_start": "प्रारंभिक स्थान",
    "planner_dest": "गंतव्य",
    "planner_notes": "अतिरिक्त नोट्स",
    "planner_button": "AI यात्रा योजना बनाएं",
    "planner_loading": "AI आपके मार्ग पर विचार कर रहा है...",
    "planner_summary": "यात्रा सारांश",
    "planner_eta": "अनुमानित आगमन",
    "planner_cost": "अनुमानित लागत",
    "footer_desc": "हम आपकी शहर नेविगेशन की परिभाषा बदल रहे हैं। जीवंत, बुद्धिमान और हमेशा समय पर।",
    "footer_platform": "प्लेटफॉर्म",
    "footer_knowledge": "ज्ञान",
    "footer_contact": "नमस्ते कहें",
    "hero_badge": "प्रीमियम यात्रा अनुभव",
    "hero_title_1": "नेविगेट करें ",
    "hero_title_2": "वाइब्रेंट पावर के साथ।",
    "cta_title_1": "सिर्फ यात्रा न करें।",
    "cta_title_2": "राज",
    "cta_title_3": " करें पटरियों पर।",
    "cta_subtitle": "क्या आप अब तक के सबसे रंगीन और कुशल ट्रांजिट अनुभव को अपनाने के लिए तैयार हैं? आपकी बस इंतजार कर रही है।",
    "cta_button_primary": "अभी शामिल हों - यह मुफ़्त है",
    "cta_button_secondary": "हमारा दृष्टिकोण",
    "feature_map_badge": "इंटरएक्टिव",
    "feature_safe_title": "सुरक्षित और सुरक्षित",
    "feature_safe_desc": "सुरक्षित यात्रा सुनिश्चित करने के लिए उन्नत सुरक्षा सुविधाएँ और घटना प्रतिक्रिया उपकरण।",
    "feature_alarm_title": "गंतव्य अलार्म",
    "feature_alarm_desc": "अपने गंतव्य स्टॉप को चिह्नित करें और जब आप पहुंचें तो हमें आपको जगाने दें।",
    "feature_community_title": "समुदाय संचालित",
    "feature_community_desc": "स्थितियों की रिपोर्ट करके और लाइव विवरणों को सत्यापित करके नेटवर्क में योगदान दें।",
    "feature_crowd_title": "भीड़ की जानकारी",
    "feature_crowd_desc": "जानें कि बस आने से पहले कितनी भरी हुई है, रीयल-टाइम ऑक्यूपेंसी ट्रैकिंग के साथ।",
    "feature_alerts_title": "सेवा अलर्ट",
    "feature_alerts_desc": "अपने मार्ग पर देरी, चक्कर और मौसम के व्यवधानों से आगे रहें।",
    "feature_nearby_title": "पास के स्टैंड",
    "feature_nearby_desc": "सबसे सटीक विवरण के लिए Google मानचित्र पर अपने पास के हर बस स्टैंड को तुरंत खोजें।",
    "map_initializing": "मानचित्र सेवा शुरू हो रही है...",
    "map_back_home": "वापस होम",
    "map_search_placeholder": "गंतव्य, बस स्टैंड, शहर खोजें...",
    "map_directions": "दिशा निर्देश प्राप्त करें",
    "cta_plan_smartly": "स्मार्ट योजना बनाएं",
    "cta_explore_map": "मानचित्र देखें",
    "cta_learn_more": "और जानें",
    "cta_set_alarm": "अलार्म सेट करें",
    "cta_join_us": "शामिल हों",
    "cta_check_occupancy": "भीड़ जांचें",
    "cta_view_alerts": "अलर्ट देखें",
    "cta_show_nearby": "पास के दिखाएं",
    "feature_smart_badge": "स्मार्ट",
    "feature_trusted_badge": "विश्वसनीय",
    "feature_onboard_badge": "ऑनबोर्ड",
    "feature_social_badge": "सामाजिक",
    "feature_critical_badge": "महत्वपूर्ण",
    "feature_external_badge": "बाहरी",
    "feature_experience_badge": "हमारा अनुभव",
    "feature_hero_title_1": "के लिए डिज़ाइन किया गया",
    "feature_hero_title_2": "साहसी",
    "feature_hero_title_3": "यात्री।",
    "feature_hero_desc": "हमने सिर्फ एक ट्रैकर नहीं बनाया। हमने एक जीवंत साथी बनाया है जो शैली और सटीकता के साथ शहरी जंगल के माध्यम से आपका मार्गदर्शन करता है।",
    "cta_rated_badge": "उपयोगकर्ताओं द्वारा 4.9/5 रेटेड",
    "cta_city_approved": "शहर द्वारा स्वीकृत",
    "cta_stat_1": "परिवहन दक्षता",
    "cta_stat_2": "नेटवर्क कवरेज",
    "cta_stat_3": "सामुदायिक विकास",
  },
  ta: {
    "nav_home": "முகப்பு",
    "nav_trip_planner": "AI பயணத் திட்டம்",
    "nav_map_search": "வரைபடத் தேடல்",
    "nav_about": "பற்றி",
    "nav_profile": "சுயவிவரம்",
    "profile_title": "எனது சுயவிவரம்",
    "profile_trips": "எனது பயண வரலாறு",
    "profile_no_trips": "பயணங்கள் எதுவும் இல்லை",
    "profile_plan_trip": "பயணத்திற்கு திட்டமிடுங்கள்",
    "profile_sign_out": "வெளியேறு",
    "profile_account_type": "கணக்கு வகை",
    "profile_standard_member": "நிலையான உறுப்பினர்",
    "profile_language": "விருப்பமான மொழி",
    "hero_title": "துடிப்பான சக்தியுடன் பயணிக்கவும்.",
    "hero_subtitle": "நகர்ப்புற போக்குவரத்தில் வண்ணத்தையும் புத்திசாலித்தனத்தையும் கொண்டு வந்துள்ளோம். ஒவ்வொரு பேருந்தையும் தடமறியுங்கள், ஒவ்வொரு பயணத்தையும் திட்டமிடுங்கள்.",
    "hero_cta": "உங்கள் பயணத்தைத் திட்டமிடுங்கள்",
    "stats_commuters": "தினசரி பயணிகள்",
    "stats_routes": "செயலில் உள்ள வழிகள்",
    "stats_buses": "நேரடி பேருந்துகள்",
    "stats_time": "சேமிக்கப்பட்ட நேரம்",
    "feature_ai_title": "AI பயணத் திட்டம்",
    "feature_ai_desc": "எங்கள் புரட்சிகரமான AI சரியான பயணத்தைப் பரிந்துரைக்க போக்குவரத்து மற்றும் வழிகளை பகுப்பாய்வு செய்கிறது.",
    "feature_map_title": "உலகளாவிய ரேடார்",
    "feature_map_desc": "எங்கள் வரைபடத்தில் சரிபார்க்கப்பட்ட நிறுத்தங்கள் மற்றும் மையங்களைக் கண்டறியவும்.",
    "planner_start": "தொடக்க இடம்",
    "planner_dest": "சேருமிடம்",
    "planner_notes": "கூடுதல் குறிப்புகள்",
    "planner_button": "AI பயணத் திட்டத்தை உருவாக்கு",
    "planner_loading": "AI உங்கள் வழியைத் திட்டமிடுகிறது...",
    "planner_summary": "பயணச் சுருக்கம்",
    "planner_eta": "மதிப்பீட்டு வருகை",
    "planner_cost": "மதிப்பீட்டு செலவு",
  },
  te: {
    "nav_home": "హోమ్",
    "nav_trip_planner": "AI ట్రిప్ ప్లానర్",
    "nav_map_search": "మ్యాప్ సెర్చ్",
    "nav_about": "గురించి",
    "nav_profile": "ప్రొఫైల్",
    "profile_title": "నా ప్రొఫైల్",
    "profile_trips": "నా ప్రయాణ చరిత్ర",
    "profile_no_trips": "ప్రయాణాలు ఏవీ లేవు",
    "profile_plan_trip": "ప్రయాణాన్ని ప్లాన్ చేయండి",
    "profile_sign_out": "సైన్ అవుట్",
    "profile_account_type": "ఖాతా రకం",
    "profile_standard_member": "సాధారణ సభ్యుడు",
    "profile_language": "ప్రాధాన్య భాష",
    "hero_title": "వైబ్రెంట్ పవర్తో నావిగేట్ చేయండి.",
    "hero_subtitle": "మేము పట్టణ రవాణాలో రంగు మరియు తెలివితేటలను తీసుకువచ్చాము. ప్రతి బస్సును ట్రాక్ చేయండి, ప్రయాణాలను ప్లాన్ చేయండి.",
    "hero_cta": "మీ ప్రయాణాన్ని ప్లాన్ చేయండి",
    "stats_commuters": "రోజువారీ ప్రయాణికులు",
    "stats_routes": "యాక్టివ్ రూట్లు",
    "stats_buses": "లైవ్ బస్సులు",
    "stats_time": "సమయం ఆదా",
    "feature_ai_title": "AI ట్రిప్ ప్లానర్",
    "feature_ai_desc": "మా విప్లవాత్మక AI సరైన ప్రయాణాన్ని సూచించడానికి ట్రాఫిక్ మరియు మార్గాలను విశ్లేషిస్తుంది.",
    "feature_map_title": "గ్లోబల్ రాడార్",
    "feature_map_desc": "మా ఇంటరాక్టివ్ మ్యాప్‌లో ధృవీకరించబడిన స్టాప్‌లు మరియు ట్రాన్సిట్ హబ్‌లను కనుగొనండి.",
    "planner_start": "ప్రారంభ స్థానం",
    "planner_dest": "గమ్యం",
    "planner_notes": "అదనపు గమనికలు",
    "planner_button": "AI ట్రిప్ ప్లాన్ జనరేట్ చేయండి",
    "planner_loading": "AI మీ మార్గాన్ని ఆలోచిస్తోంది...",
    "planner_summary": "ప్రయాణ సారాంశం",
    "planner_eta": "అంచనా రాక సమయం",
    "planner_cost": "అంచనా ఖర్చు",
  },
  kn: {
    "nav_home": "ಮುಖಪುಟ",
    "nav_trip_planner": "AI ಟ್ರಿಪ್ ಪ್ಲಾನರ್",
    "nav_map_search": "ಮ್ಯಾಪ್ ಹುಡುಕಾಟ",
    "nav_about": "ಬಗ್ಗೆ",
    "nav_profile": "ಪ್ರೊಫೈಲ್",
    "profile_title": "ನನ್ನ ಪ್ರೊಫೈಲ್",
    "profile_trips": "ನನ್ನ ಪ್ರಯಾಣದ ಇತಿಹಾಸ",
    "profile_no_trips": "ಯಾವುದೇ ಪ್ರಯಾಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ",
    "profile_plan_trip": "ಪ್ರಯಾಣವನ್ನು ಯೋಜಿಸಿ",
    "profile_sign_out": "ಸೈನ್ ಔಟ್",
    "profile_account_type": "ಖಾತೆಯ ಪ್ರಕಾರ",
    "profile_standard_member": "ಸಾಮಾನ್ಯ ಸದಸ್ಯ",
    "profile_language": "ಆದ್ಯತೆಯ ಭಾಷೆ",
    "hero_title": "ವೈಬ್ರೆಂಟ್ ಪವರ್‌ನೊಂದಿಗೆ ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿ.",
    "hero_subtitle": "ನಾವು ನಗರ ಸಾರಿಗೆಯಲ್ಲಿ ಬಣ್ಣ ಮತ್ತು ಬುದ್ಧಿವಂತಿಕೆಯನ್ನು ತಂದಿದ್ದೇವೆ. ಪ್ರತಿ ಬಸ್ ಅನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಪ್ರತಿಯೊಂದು ಪ್ರಯಾಣವನ್ನು ಯೋಜಿಸಿ.",
    "hero_cta": "ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಯೋಜಿಸಿ",
    "stats_commuters": "ದೈನಂದಿನ ಪ್ರಯಾಣಿಕರು",
    "stats_routes": "ಸಕ್ರಿಯ ಮಾರ್ಗಗಳು",
    "stats_buses": "ಲೈವ್ ಬಸ್‌ಗಳು",
    "stats_time": "ಉಳಿಸಿದ ಸಮಯ",
    "feature_ai_title": "AI ಟ್ರಿಪ್ ಪ್ಲಾನರ್",
    "feature_ai_desc": "ನಮ್ಮ ಕ್ರಾಂತಿಕಾರಿ AI ಪರಿಪೂರ್ಣ ಪ್ರಯಾಣವನ್ನು ಸೂಚಿಸಲು ಟ್ರಾಫಿಕ್ ಮತ್ತು ಮಾರ್ಗಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.",
    "feature_map_title": "ಗ್ಲೋಬಲ್ ರಾಡಾರ್",
    "feature_map_desc": "ನಮ್ಮ ಸಂವಾದಾತ್ಮಕ ನಕ್ಷೆಯಲ್ಲಿ ಪರಿಶೀಲಿಸಿದ ನಿಲ್ದಾಣಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.",
    "planner_start": "ಪ್ರಾರಂಭದ ಸ್ಥಳ",
    "planner_dest": "ಗಮ್ಯಸ್ಥಾನ",
    "planner_notes": "ಹೆಚ್ಚುವರಿ ಟಿಪ್ಪಣಿಗಳು",
    "planner_button": "AI ಟ್ರಿಪ್ ಪ್ಲಾನ್ ರಚಿಸಿ",
    "planner_loading": "AI ನಿಮ್ಮ ಮಾರ್ಗವನ್ನು ಯೋಜಿಸುತ್ತಿದೆ...",
    "planner_summary": "ಪ್ರಯಾಣದ ಸಾರಾಂಶ",
    "planner_eta": "ಅಂದಾಜು ಆಗಮನ",
    "planner_cost": "ಅಂದಾಜು ವೆಚ್ಚ",
  },
  ml: {
    "nav_home": "ഹോം",
    "nav_trip_planner": "AI ട്രിപ്പ് പ്ലാനർ",
    "nav_map_search": "മാപ്പ് സെർച്ച്",
    "nav_about": "ഞങ്ങളെക്കുറിച്ച്",
    "nav_profile": "പ്രൊഫൈൽ",
    "profile_title": "എന്റെ പ്രൊഫൈൽ",
    "profile_trips": "യാത്രാ ചരിത്രം",
    "profile_no_trips": "യാത്രകളൊന്നും കണ്ടെത്തിയില്ല",
    "profile_plan_trip": "യാത്ര പ്ലാൻ ചെയ്യുക",
    "profile_sign_out": "സൈൻ ഔട്ട്",
    "profile_account_type": "അക്കൗണ്ട് തരം",
    "profile_standard_member": "സ്റ്റാൻഡേർഡ് അംഗം",
    "profile_language": "താൽപ്പര്യമുള്ള ഭാഷ",
    "hero_title": "വൈബ്രന്റ് പവർ ഉപയോഗിച്ച് നാവിഗേറ്റ് ചെയ്യുക.",
    "hero_subtitle": "നഗര ഗതാഗതത്തിൽ ഞങ്ങൾ നിറവും ബുദ്ധിയും നൽകിയിട്ടുണ്ട്. ഓരോ ബസ്സും ട്രാക്ക് ചെയ്യുക, യാത്രകൾ പ്ലാൻ ചെയ്യുക.",
    "hero_cta": "യാത്ര പ്ലാൻ ചെയ്യുക",
    "stats_commuters": "പ്രതിദിന യാത്രക്കാർ",
    "stats_routes": "സജീവ റൂട്ടുകൾ",
    "stats_buses": "ലൈവ് ബസ്സുകൾ",
    "stats_time": "ലാഭിച്ച സമയം",
    "feature_ai_title": "AI ട്രിപ്പ് പ്ലാനർ",
    "feature_ai_desc": "മികച്ച യാത്ര നിർദ്ദേശിക്കുന്നതിനായി ഞങ്ങളുടെ AI ട്രാഫിക്കും റൂട്ടുകളും വിശകലനം ചെയ്യുന്നു.",
    "feature_map_title": "ഗ്ലോബൽ റഡാർ",
    "feature_map_desc": "മാപ്പിൽ പരിശോധിച്ച സ്റ്റോപ്പുകളും ഹബ്ബുകളും കണ്ടെത്തുക.",
    "planner_start": "തുടങ്ങുന്ന സ്ഥലം",
    "planner_dest": "ലക്ഷ്യസ്ഥാനം",
    "planner_notes": "കൂടുതൽ കുറിപ്പുകൾ",
    "planner_button": "AI യാത്രാ പ്ലാൻ ഉണ്ടാക്കുക",
    "planner_loading": "AI നിങ്ങളുടെ റൂട്ട് പ്ലാൻ ചെയ്യുന്നു...",
    "planner_summary": "യാത്രാ സംഗ്രഹം",
    "planner_eta": "എത്തുമെന്ന് കരുതുന്ന സമയം",
    "planner_cost": "യാത്രാ ചിലവ്",
  },
  mr: {
    "nav_home": "होम",
    "nav_trip_planner": "AI ट्रिप प्लॅनर",
    "nav_map_search": "मॅप शोध",
    "nav_about": "बद्दल",
    "nav_profile": "प्रोफाइल",
    "profile_title": "माझी प्रोफाइल",
    "profile_trips": "माझा प्रवास इतिहास",
    "profile_no_trips": "प्रवास आढळला नाही",
    "profile_plan_trip": "प्रवासाचे नियोजन करा",
    "profile_sign_out": "साइन आउट",
    "profile_account_type": "खाते प्रकार",
    "profile_standard_member": "मानक सदस्य",
    "profile_language": "पसंतीची भाषा",
    "hero_title": "व्हायब्रंट पॉवरसह नेव्हिगेट करा.",
    "hero_subtitle": "आम्ही शहरी वाहतुकीत रंग आणि बुद्धिमत्ता आणली आहे. प्रत्येक बस ट्रॅक करा, प्रत्येक सहलीचे नियोजन करा.",
    "hero_cta": "सहलीचे नियोजन करा",
    "stats_commuters": "दैनंदिन प्रवासी",
    "stats_routes": "सक्रिय मार्ग",
    "stats_buses": "लाइव्ह बसेस",
    "stats_time": "वेळेची बचत",
    "feature_ai_title": "AI ट्रिप प्लॅनर",
    "feature_ai_desc": "आमचे क्रांतिकारक AI परिपूर्ण प्रवासाचा सल्ला देण्यासाठी ट्रॅफिक आणि मार्गांचे विश्लेषण करते.",
    "feature_map_title": "ग्लोबल रडार",
    "feature_map_desc": "आमच्या नकाशावर सत्यापित थांबे आणि ट्रान्झिट हब शोधा.",
    "planner_start": "सुरुवातीचे ठिकाण",
    "planner_dest": "गंतव्यस्थान",
    "planner_notes": "जादा टिपा",
    "planner_button": "AI ट्रिप प्लॅन तयार करा",
    "planner_loading": "AI तुमच्या मार्गाचा विचार करत आहे...",
    "planner_summary": "प्रवास सारांश",
    "planner_eta": "अंदाजित आगमन",
    "planner_cost": "अंदाजित खर्च",
  },
  bn: {
    "nav_home": "হোম",
    "nav_trip_planner": "AI ট্রিপ প্ল্যানার",
    "nav_map_search": "ম্যাপ সার্চ",
    "nav_about": "সম্পর্কে",
    "nav_profile": "প্রোফাইল",
    "profile_title": "আমার প্রোফাইল",
    "profile_trips": "ভ্রমণ ইতিহাস",
    "profile_no_trips": "কোন ভ্রমণ পাওয়া যায়নি",
    "profile_plan_trip": "ভ্রমণ পরিকল্পনা করুন",
    "profile_sign_out": "সাইন আউট",
    "profile_account_type": "অ্যাকাউন্টের ধরন",
    "profile_standard_member": "স্ট্যান্ডার্ড সদস্য",
    "profile_language": "পছন্দসই ভাষা",
    "hero_title": "ভাইব্রেন্ট পাওয়ার দিয়ে নেভিগেট করুন।",
    "hero_subtitle": "আমরা নগর যাতায়াতে রঙ এবং বুদ্ধিমত্তা নিয়ে এসেছি। প্রতিটি বাস ট্র্যাক করুন, জীবন সহজ করুন।",
    "hero_cta": "আপনার ভ্রমণ পরিকল্পনা করুন",
    "stats_commuters": "দৈনিক যাত্রী",
    "stats_routes": "সক্রিয় রুট",
    "stats_buses": "লাইভ বাস",
    "stats_time": "সময় সাশ্রয়",
    "feature_ai_title": "AI ট্রিপ প্ল্যানার",
    "feature_ai_desc": "আমাদের বিপ্লবী AI সঠিক পথের পরামর্শ দেওয়ার জন্য ট্রাফিক এবং রুট বিশ্লেষণ করে।",
    "feature_map_title": "গ্লোবাল রাডার",
    "feature_map_desc": "ম্যাপে যাচাইকৃত বাস স্টপ এবং ট্রানজিট হাব খুঁজে বের করুন।",
    "planner_start": "শুরু করার স্থান",
    "planner_dest": "গন্তব্য",
    "planner_notes": "অতিরিক্ত নোট",
    "planner_button": "AI ট্রিপ প্ল্যান তৈরি করুন",
    "planner_loading": "AI আপনার রুট পরিকল্পনা করছে...",
    "planner_summary": "ভ্রমণের সারাংশ",
    "planner_eta": "আনুমানিক আগমন",
    "planner_cost": "আনুমানিক খরচ",
  },
  gu: {
    "nav_home": "હોમ",
    "nav_trip_planner": "AI ટ્રિપ પ્લાનર",
    "nav_map_search": "નકશા શોધ",
    "nav_about": "વિશે",
    "nav_profile": "પ્રોફાઇલ",
    "profile_title": "મારી પ્રોફાઇલ",
    "profile_trips": "મારો પ્રવાસ ઇતિહાસ",
    "profile_no_trips": "કોઈ પ્રવાસ મળ્યો નથી",
    "profile_plan_trip": "પ્રવાસનું આયોજન કરો",
    "profile_sign_out": "સાઇન આઉટ",
    "profile_account_type": "ખાતાનો પ્રકાર",
    "profile_standard_member": "સ્ટાન્ડર્ડ સભ્ય",
    "profile_language": "પસંદગીની ભાષા",
    "hero_title": "વાઇબ્રન્ટ પાવર સાથે નેવિગેટ કરો.",
    "hero_subtitle": "અમે શહેરી પરિવહનમાં રંગ અને બુદ્ધિ લાવ્યા છીએ. દરેક બસને ટ્રૅક કરો, પ્રવાસનું આયોજન કરો.",
    "hero_cta": "તમારા પ્રવાસનું આયોજન કરો",
    "stats_commuters": "દૈનિક મુસાફરો",
    "stats_routes": "સક્રિય રૂટ્સ",
    "stats_buses": "લાઇવ બસો",
    "stats_time": "સમય બચાવ્યો",
    "feature_ai_title": "AI ટ્રિપ પ્લાનર",
    "feature_ai_desc": "અમારું ક્રાંતિકારી AI સંપૂર્ણ પ્રવાસ સૂચવવા માટે ટ્રાફિક અને રૂટનું વિશ્લેષણ કરે છે.",
    "feature_map_title": "ગ્લોબલ રડાર",
    "feature_map_desc": "સીધા અમારા નકશા પર ચકાસાયેલ સ્ટોપ્સ અને હબ શોધો.",
    "planner_start": "શરૂઆતનું સ્થળ",
    "planner_dest": "ગંતવ્ય",
    "planner_notes": "વધારાની નોંધો",
    "planner_button": "AI ટ્રિપ પ્લાન તૈયાર કરો",
    "planner_loading": "AI તમારા રૂટ વિશે વિચારી રહ્યું છે...",
    "planner_summary": "પ્રવાસ સારાંશ",
    "planner_eta": "અંદાજિત આગમન",
    "planner_cost": "અંદાજિત ખર્ચ",
  },
  pa: {
    "nav_home": "ਹੋਮ",
    "nav_trip_planner": "AI ਟ੍ਰਿਪ ਪਲਾਨਰ",
    "nav_map_search": "ਨਕਸ਼ਾ ਖੋਜ",
    "nav_about": "ਬਾਰੇ",
    "nav_profile": "ਪ੍ਰੋਫਾਈਲ",
    "profile_title": "ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ",
    "profile_trips": "ਮੇਰਾ ਯਾਤਰਾ ਇਤਿਹਾਸ",
    "profile_no_trips": "ਕੋਈ ਯਾਤਰਾ ਨਹੀਂ ਮਿਲੀ",
    "profile_plan_trip": "ਯਾਤਰਾ ਦੀ ਯੋਜਨਾ ਬਣਾਓ",
    "profile_sign_out": "ਸਾਈਨ ਆਊਟ",
    "profile_account_type": "ਖਾਤਾ ਕਿਸਮ",
    "profile_standard_member": "ਸਟੈਂਡਰਡ ਮੈਂਬਰ",
    "profile_language": "ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ",
    "hero_title": "ਵਾਈਬ੍ਰੈਂਟ ਪਾਵਰ ਨਾਲ ਨੈਵੀਗੇਟ ਕਰੋ।",
    "hero_subtitle": "ਅਸੀਂ ਸ਼ਹਿਰੀ ਟ੍ਰਾਂਜ਼ਿਟ ਵਿੱਚ ਰੰਗ ਅਤੇ ਬੁੱਧੀ ਲਿਆਏ ਹਾਂ। ਹਰ ਬੱਸ ਨੂੰ ਟ੍ਰੈਕ ਕਰੋ, ਯਾਤਰਾ ਦੀ ਯੋਜਨਾ ਬਣਾਓ।",
    "hero_cta": "ਪਲਾਨ ਬਣਾਓ",
    "stats_commuters": "ਰੋਜ਼ਾਨਾ ਯਾਤਰੀ",
    "stats_routes": "ਐਕਟਿਵ ਰੂਟ",
    "stats_buses": "ਲਾਈਵ ਬੱਸਾਂ",
    "stats_time": "ਬਚਾਇਆ ਸਮਾਂ",
    "feature_ai_title": "AI ਟ੍ਰਿਪ ਪਲਾਨਰ",
    "feature_ai_desc": "ਸਾਡਾ ਕ੍ਰਾਂਤੀਕਾਰੀ AI ਸਹੀ ਯਾਤਰਾ ਦਾ ਸੁਝਾਅ ਦੇਣ ਲਈ ਟ੍ਰੈਫਿਕ ਅਤੇ ਰੂਟਾਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦਾ ਹੈ।",
    "feature_map_title": "ਗਲੋਬਲ ਰਡਾਰ",
    "feature_map_desc": "ਸਾਡੇ ਨਕਸ਼ੇ 'ਤੇ ਸਹੀ ਸਟਾਪਾਂ ਅਤੇ ਟ੍ਰਾਂਜ਼ਿਟ ਹੱਬਾਂ ਦੀ ਖੋਜ ਕਰੋ।",
    "planner_start": "ਸ਼ੁਰੂਆਤੀ ਸਥਾਨ",
    "planner_dest": "ਮੰਜ਼ਿਲ",
    "planner_notes": "ਵਾਧੂ ਨੋਟਸ",
    "planner_button": "AI ਯਾਤਰਾ ਪਲਾਨ ਬਣਾਓ",
    "planner_loading": "AI ਤੁਹਾਡੇ ਰੂਟ 'ਤੇ ਵਿਚਾਰ ਕਰ ਰਿਹਾ ਹੈ...",
    "planner_summary": "ਯਾਤਰਾ ਦਾ ਸਾਰ",
    "planner_eta": "ਅੰਦਾਜ਼ਨ ਆਗਮਨ",
    "planner_cost": "ਅੰਦਾਜ਼ਨ ਲਾਗਤ",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('app_language') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
